# for davmail set config(spamfilter.ini) values:
# host = localhost
# port = 1143
# ssl = False
#
# set davmail.url in davmail.properties
# and do docker-compose
version: "3.7"
services:
  davmail:
    image: jberrenberg/davmail
    volumes:
      # local properties : container properties
      - "./davmail.properties:/etc/davmail/davmail.properties"
    networks:
      - shared
# smtp port if needed
# ports:
#      - "1025:1025"
  spamfilter:
    # container defined in dockerfile
    build: .
    networks:
      - shared
networks:
  shared:
    driver: bridge


